/*  THIS FILE INSERTS TEST DATA INTO EACH OF OUR TABLES */

-- INSERT VALUES INTO repairMachine TABLE
INSERT INTO repairMachine VALUES();
INSERT INTO repairMachine VALUES();
INSERT INTO repairMachine VALUES();
INSERT INTO repairMachine VALUES();
INSERT INTO repairMachine VALUES();

-- INSERT VALUES INTO problem TABLE
INSERT INTO problem VALUES();
INSERT INTO problem VALUES();
INSERT INTO problem VALUES();
INSERT INTO problem VALUES();
INSERT INTO problem VALUES();

-- INSERT VALUES INTO bill TABLE
INSERT INTO bill VALUES();
INSERT INTO bill VALUES();
INSERT INTO bill VALUES();
INSERT INTO bill VALUES();
INSERT INTO bill VALUES();

-- INSERT VALUES INTO customer TABLE
INSERT INTO customer VALUES();
INSERT INTO customer VALUES();
INSERT INTO customer VALUES();
INSERT INTO customer VALUES();
INSERT INTO customer VALUES();

-- INSERT VALUES INTO serviceItem TABLE
INSERT INTO serviceItem VALUES();
INSERT INTO serviceItem VALUES();
INSERT INTO serviceItem VALUES();
INSERT INTO serviceItem VALUES();
INSERT INTO serviceItem VALUES();

-- INSERT VALUES INTO contract TABLE
INSERT INTO contract VALUES();
INSERT INTO contract VALUES();
INSERT INTO contract VALUES();
INSERT INTO contract VALUES();
INSERT INTO contract VALUES();

-- INSERT VALUES INTO group TABLE
INSERT INTO group VALUES();
INSERT INTO group VALUES();
INSERT INTO group VALUES();
INSERT INTO group VALUES();
INSERT INTO group VALUES();

-- INSERT VALUES INTO repairPerson TABLE
INSERT INTO repairPerson VALUES();
INSERT INTO repairPerson VALUES();
INSERT INTO repairPerson VALUES();
INSERT INTO repairPerson VALUES();
INSERT INTO repairPerson VALUES();
